---
  - name: Install otehr packages
    yum:
      name: ['git', 'unzip', 'epel-release', 'vim', 'wget']
      state: latest

  - name:  Download AWS Cli
    get_url: 
      url: "{{ aws_cli_url }}"
      dest: "/tmp/"

  - name: Unzip AWS cli zip archive
    unarchive:
      src: /tmp/{{ aws_cli_url | basename }}
      dest: /tmp/
      remote_src: yes

  - name: Install AWS Cli 
    command: "/tmp/aws/install"
    register: command_result
    failed_when: "'Found preexisting AWS CLI installation' in command_result.stderr_lines"

  - name:  Download nodejs 12 repo file
    get_url: 
      url: "{{ nodejs_url }}"
      dest: "/tmp/"

  - name: Add nodejs 12.x repo
    command: 'bash /tmp/{{ nodejs_url | basename }}'

  - name: install nodejs
    yum:
      name: ['nodejs']
      state: present
 
  - name: Adding Git credential with IAM roles to access CodeCommit
    command: "{{ item }}"
    with_items:
      - "git config --global credential.helper '!aws codecommit credential-helper $@'"
      - "git config --global credential.UseHttpPath true"