---
- hosts: tableaumaster
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - role: selinux-disable
    - role: tableau-initial
    - role: tableau-initial-activation
  
- hosts: tableaunodes
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - role: selinux-disable
    - role: tableau-aditional-install

- hosts: tableaumaster
  become: true
  become_method: sudo
  gather_facts: no
  roles:
    - role: tableau-master-clustersetup
    - role: tableau-processes-for-extra-nodes 
    - role: tableau-trusted-authentication
    #- role: enabble-openIDP-authentication