- hosts: newhost
  user: ansible
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    php_options:
     max_execution_time: 600
     expose_php: "Off"
     max_input_time: 600
     memory_limit: "512M"
     error_reporting: "E_ERROR"
     display_errors: "Off"
     post_max_size: "100M"
     file_uploads: "On"
     upload_max_filesize: "50M"
     max_file_uploads: 20
     date.timezone: "America/New_York"
     error_log: "/var/log/php_errors.log"
     max_input_nesting_level: 64
     short_open_tag: "On"
     session.save_path: "/var/lib/php/session"
     session.gc_maxlifetime: 86400
     session.cache_expire: 180
    php2_options: #Those that not needed space between =
     soap.wsdl_cache_enabled: 0
     soap.wsdl_cache_ttl: 0
    php3_options: #Those that have space between ; 
     max_input_vars: 100000

  tasks:
   - name: Editing php.ini
     replace:
      path: /etc/php.ini
      regexp: '^[;]*{{ item.key }}.*$'
      replace: '{{ item.key }} = {{ item.value }}'
     with_dict: "{{ php_options }}"

   - name: Editing much more php.ini
     replace:
      path: /etc/php.ini
      regexp: '^[;]*{{ item.key }}.*$'
      replace: '{{ item.key }}={{ item.value }}'
     with_dict: "{{ php2_options }}"

   - name: Editing more to php.ini
     replace:
      path: /etc/php.ini
      regexp: '^[;] {{ item.key }}.*$'
      replace: '{{ item.key }} = {{ item.value }}'
     with_dict: "{{ php3_options }}"

   - name: Restarting apache2
     systemd: name=apache2 state=started daemon_reload=yes
