---
- name: Finding the Tableau customer bin directory and version
  shell: ls -d /opt/tableau/tableau_server/packages/customer-bin*
  register: tsm_bin_dir

- debug: msg={{ tsm_bin_dir.stdout }}


- name: Configure OpenIDP Authentication
  command: '{{ tsm_bin_dir.stdout }}/tsm authentication openid configure --client-id "{{ openid_clientid }}" --client-secret "{{ openid_client_secret }}" --config-url "https://{{ okta_domain }}/.well-known/openid-configuration" --return-url "{{ tableau_external_url }}"'

- name: Enable OpenIDP Authentication
  command: '{{ tsm_bin_dir.stdout }}/tsm authentication openid enable' 

- name: Apply pending changes
  command: '{{ tsm_bin_dir.stdout }}/tsm pending-changes apply --ignore-prompt'
